export const dayBlocks = [
  {
    id: 'marta-day-12',
    person: 'Marta R.',
    category: 'Musica',
    initials: 'MR',
    color: '#cfe0ff',
    day: 12,
    total: 30,
    dateLabel: '38 min fa',
    entries: [
      {
        id: 'marta-12-text',
        type: 'traguardo',
        text: 'Per la prima volta ho cambiato tra Sol e Do senza fermarmi. Lentissimo, ma il suono c’era tutto.',
        sharedRoomWith: true,
        signals: { fire: 8, brick: 4, map: 2, zap: 1 },
      },
      {
        id: 'marta-12-audio',
        type: 'aggiornamento',
        text: 'Ho registrato il passaggio per confrontarlo con il Giorno 1.',
        sharedRoomWith: true,
        media: 'audio',
        signals: { fire: 3, brick: 1, map: 2, zap: 4 },
      },
      {
        id: 'marta-12-photo',
        type: 'aggiornamento',
        text: 'La posizione della mano che finalmente non mi irrigidisce il polso.',
        sharedRoomWith: true,
        media: 'foto',
        signals: { fire: 2, brick: 3, map: 1, zap: 0 },
      },
    ],
  },
  {
    id: 'luca-day-9',
    person: 'Luca M.',
    category: 'Musica',
    initials: 'LM',
    color: '#ffd5c5',
    day: 9,
    total: 30,
    dateLabel: '2 ore fa',
    entries: [{
      id: 'luca-9-block',
      type: 'blocco',
      text: 'Cambio accordi ancora sporco. Oggi ho abbassato il metronomo a 48 bpm e lavorato solo sul movimento della mano sinistra.',
      sharedRoomWith: true,
      tags: ['#cambio-accordi', '#dita-doloranti'],
      signals: { fire: 3, brick: 7, map: 1, zap: 0 },
    }],
  },
  {
    id: 'elena-day-18',
    person: 'Elena V.',
    category: 'Musica',
    initials: 'EV',
    color: '#d8ead9',
    day: 18,
    total: 30,
    dateLabel: 'ieri',
    entries: [{
      id: 'elena-18-pivot',
      type: 'cambio rotta',
      text: 'Ho smesso di inseguire cinque canzoni insieme. Per questa settimana ne tengo una sola: “Stand by Me”.',
      recipeClonedFrom: true,
      signals: { fire: 5, brick: 2, map: 6, zap: 2 },
    }],
  },
  {
    id: 'federico-day-30',
    person: 'Federico G.',
    category: 'Musica',
    initials: 'FG',
    color: '#fff0b8',
    day: 30,
    total: 30,
    dateLabel: '2 giorni fa',
    entries: [{
      id: 'federico-30-completion',
      type: 'completamento',
      text: 'Trenta giorni dopo, riesco a suonare il brano dall’inizio alla fine. Non perfetto: mio.',
      signals: { fire: 16, brick: 9, map: 7, zap: 5, vetta: 12 },
    }],
  },
  {
    id: 'giorgio-day-9',
    person: 'Giorgio L.',
    category: 'Benessere',
    initials: 'GL',
    color: '#ffe0c5',
    day: 9,
    total: 21,
    dateLabel: '51 min fa',
    entries: [{
      id: 'giorgio-9-routine',
      type: 'traguardo',
      text: 'Il telefono è rimasto in cucina fino a colazione finita. La mattina sembrava avere più spazio.',
      recipeClonedFrom: true,
      signals: { fire: 11, brick: 5, map: 8, zap: 2 },
    }],
  },
  {
    id: 'sara-day-16',
    person: 'Sara N.',
    category: 'Movimento',
    initials: 'SN',
    color: '#d2ead8',
    day: 16,
    total: 45,
    dateLabel: '1 ora fa',
    entries: [{
      id: 'sara-16-run',
      type: 'aggiornamento',
      text: 'Tre chilometri alternando corsa e camminata. Ho chiuso con fiato sufficiente per continuare.',
      sharedRoomWith: true,
      signals: { fire: 7, brick: 6, map: 2, zap: 3 },
    }],
  },
  {
    id: 'nadia-day-22',
    person: 'Nadia P.',
    category: 'Cucina',
    initials: 'NP',
    color: '#d9ead7',
    day: 22,
    total: 60,
    dateLabel: '3 ore fa',
    entries: [{
      id: 'nadia-22-pantry',
      type: 'cambio rotta',
      text: 'Ho preparato una base comune per tre cene. Meno ingredienti, ma nessun piatto sembrava una copia.',
      signals: { fire: 4, brick: 8, map: 9, zap: 1 },
    }],
  },
  {
    id: 'anna-day-10',
    person: 'Anna C.',
    category: 'Lettura',
    initials: 'AC',
    color: '#e8ddff',
    day: 10,
    total: 30,
    dateLabel: '5 ore fa',
    entries: [{
      id: 'anna-10-notes',
      type: 'aggiornamento',
      text: 'Dieci pagine e tre righe scritte a libro chiuso. Oggi ricordo il punto, non soltanto la frase.',
      sharedRoomWith: true,
      signals: { fire: 6, brick: 3, map: 7, zap: 2 },
    }],
  },
  {
    id: 'chiara-day-6',
    person: 'Chiara B.',
    category: 'Creatività',
    initials: 'CB',
    color: '#ffd6dd',
    day: 6,
    total: 30,
    dateLabel: 'ieri',
    entries: [{
      id: 'chiara-6-sketch',
      type: 'blocco',
      text: 'Continuavo ad aprire nuovi schizzi. Oggi ne ho scelto uno e ho lavorato soltanto sui volumi.',
      signals: { fire: 3, brick: 5, map: 4, zap: 6 },
    }],
  },
]

export const userQuests = [
  { id: 'quest-guitar', roomId: 'music-guitar-mar', title: 'Basi della chitarra', category: 'Musica', day: 12, total: 30, status: 'active', color: '#cfe0ff', companions: 8, nextStep: 'Prima canzone' },
  { id: 'quest-reading', roomId: 'reading-ten-pages-jul', title: 'Dieci pagine che restano', category: 'Lettura', day: 8, total: 30, status: 'active', color: '#e8ddff', companions: 6, nextStep: 'Appunti a libro chiuso' },
  { id: 'quest-running', roomId: 'movement-5k-spring', title: 'Correre i primi 5 km', category: 'Movimento', day: 16, total: 45, status: 'paused', color: '#d2ead8', companions: 11, nextStep: 'Ripresa graduale' },
  { id: 'quest-phone', roomId: 'wellbeing-phone-june', title: '21 mattine senza telefono', category: 'Benessere', day: 21, total: 21, status: 'completed', color: '#ffe0c5', companions: 14, nextStep: 'Percorso concluso' },
  { id: 'quest-cooking', roomId: 'cooking-smart-pantry', title: 'Otto piatti, una spesa intelligente', category: 'Cucina', day: 60, total: 60, status: 'completed', color: '#d9ead7', companions: 9, nextStep: 'Ricetta pubblicata' },
]

export const roomCohorts = [
  { id: 'music-guitar-jan', title: 'Basi della chitarra', category: 'Musica', startedLabel: 'iniziato a gennaio', members: 24, day: 26, total: 30, color: '#cfe0ff' },
  { id: 'music-guitar-mar', title: 'Basi della chitarra', category: 'Musica', startedLabel: 'iniziato a marzo', members: 18, day: 12, total: 30, color: '#dbe5ff' },
  { id: 'music-song-june', title: 'La prima canzone intera', category: 'Musica', startedLabel: 'iniziato a giugno', members: 12, day: 8, total: 30, color: '#fff0b8' },
  { id: 'wellbeing-phone-june', title: '21 mattine senza telefono', category: 'Benessere', startedLabel: 'iniziato a giugno', members: 14, day: 9, total: 21, color: '#ffe0c5' },
  { id: 'movement-5k-spring', title: 'Correre i primi 5 km', category: 'Movimento', startedLabel: 'iniziato in primavera', members: 11, day: 16, total: 45, color: '#d2ead8' },
  { id: 'cooking-smart-pantry', title: 'Una spesa, otto piatti', category: 'Cucina', startedLabel: 'iniziato a maggio', members: 9, day: 22, total: 60, color: '#d9ead7' },
  { id: 'reading-ten-pages-jul', title: 'Dieci pagine che restano', category: 'Lettura', startedLabel: 'iniziato a luglio', members: 6, day: 8, total: 30, color: '#e8ddff' },
  { id: 'creative-one-sketch', title: 'Uno schizzo al giorno', category: 'Creatività', startedLabel: 'iniziato a luglio', members: 15, day: 6, total: 30, color: '#ffd6dd' },
]

export const questsCompleted = [
  {
    id: 1,
    category: 'Musica',
    title: 'I miei primi 4 accordi senza scorciatoie',
    author: 'Marta Rinaldi',
    authorVerifiedVia: 'quest',
    publishedByCoach: true,
    duration: '30 giorni',
    success: '84%',
    clones: 126,
    recencyDays: 12,
    color: '#cfe0ff',
    path: ['Postura', 'Dita', 'Cambi', 'Prima canzone'],
    listing: {
      type: 'corso',
      coach: 'Marta Rinaldi',
      rating: '4.8 · 42 recensioni',
      price: 39,
      premiumPrice: 69,
      hasPrivateRoom: true,
      hasLiveSessions: true,
      activationStatus: 'attiva',
      activationDetail: '18/24 posti',
      level: 'Principiante',
    },
  },
  {
    id: 2,
    category: 'Benessere',
    title: '21 mattine senza telefono',
    author: 'Giorgio Lodi',
    authorVerifiedVia: 'quest',
    publishedByCoach: false,
    duration: '21 giorni',
    success: '77%',
    clones: 94,
    recencyDays: 6,
    color: '#ffe0c5',
    path: ['Sveglia', 'Attrito', 'Routine', 'Autonomia'],
    listing: null,
  },
  {
    id: 3,
    category: 'Cucina',
    title: 'Otto piatti, una spesa intelligente',
    author: 'Nadia Pavesi',
    authorVerifiedVia: 'credentials',
    publishedByCoach: true,
    duration: '60 giorni',
    success: '71%',
    clones: 68,
    recencyDays: 24,
    color: '#d9ead7',
    path: ['Dispensa', 'Basi', 'Tempi', 'Menu'],
    listing: {
      type: 'consulenza',
      coach: 'Nadia Pavesi',
      rating: '4.7 · 19 recensioni',
      price: 45,
      premiumPrice: null,
      hasPrivateRoom: false,
      hasLiveSessions: true,
      activationStatus: null,
      activationDetail: 'Videochiamata individuale · 45 min',
      level: 'Intermedio',
    },
  },
  {
    id: 4,
    category: 'Lettura',
    title: 'Dieci pagine che restano',
    author: 'Anna Costa',
    authorVerifiedVia: 'quest',
    publishedByCoach: true,
    duration: '30 giorni',
    success: '89%',
    clones: 201,
    recencyDays: 18,
    color: '#e8ddff',
    path: ['Scelta', 'Ritmo', 'Appunti', 'Sintesi'],
    listing: {
      type: 'risorsa',
      coach: 'Anna Costa',
      rating: '4.9 · 18 recensioni',
      price: 18,
      premiumPrice: null,
      hasPrivateRoom: false,
      hasLiveSessions: false,
      activationStatus: null,
      activationDetail: 'PDF + checklist · disponibile subito',
      level: 'Principiante',
    },
  },
  {
    id: 5,
    category: 'Movimento',
    title: 'Correre i primi 5 km con costanza',
    author: 'Sara Neri',
    authorVerifiedVia: 'credentials',
    publishedByCoach: true,
    duration: '45 giorni',
    success: '81%',
    clones: 113,
    recencyDays: 3,
    color: '#d2ead8',
    path: ['Camminata', 'Fiato', 'Ritmo', 'Primi 5 km'],
    listing: {
      type: 'corso',
      coach: 'Sara Neri',
      rating: '4.7 · 31 recensioni',
      price: 29,
      premiumPrice: 54,
      hasPrivateRoom: true,
      hasLiveSessions: false,
      activationStatus: 'in_attesa',
      activationDetail: '7/10 iscritti, si attiva entro il 20 luglio',
      level: 'Principiante',
    },
  },
]
