export const dayBlocks = [
  {
    id: 'marta-day-12',
    person: 'Marta R.',
    initials: 'MR',
    color: '#cfe0ff',
    day: 12,
    total: 30,
    dateLabel: '38 min fa',
    entries: [
      {
        id: 'marta-12-text',
        type: 'traguardo',
        text: 'Per la prima volta ho cambiato tra Sol e Do senza fermarmi. Lentissimo, ma il suono c’era tutto.',
        signals: { fire: 8, brick: 4, map: 2, zap: 1 },
      },
      {
        id: 'marta-12-audio',
        type: 'aggiornamento',
        text: 'Ho registrato il passaggio per confrontarlo con il Giorno 1.',
        media: 'audio',
        signals: { fire: 3, brick: 1, map: 2, zap: 4 },
      },
      {
        id: 'marta-12-photo',
        type: 'aggiornamento',
        text: 'La posizione della mano che finalmente non mi irrigidisce il polso.',
        media: 'foto',
        signals: { fire: 2, brick: 3, map: 1, zap: 0 },
      },
    ],
  },
  {
    id: 'luca-day-9',
    person: 'Luca M.',
    initials: 'LM',
    color: '#ffd5c5',
    day: 9,
    total: 30,
    dateLabel: '2 ore fa',
    entries: [{
      id: 'luca-9-block',
      type: 'blocco',
      text: 'Cambio accordi ancora sporco. Oggi ho abbassato il metronomo a 48 bpm e lavorato solo sul movimento della mano sinistra.',
      tags: ['#cambio-accordi', '#dita-doloranti'],
      signals: { fire: 3, brick: 7, map: 1, zap: 0 },
    }],
  },
  {
    id: 'elena-day-18',
    person: 'Elena V.',
    initials: 'EV',
    color: '#d8ead9',
    day: 18,
    total: 30,
    dateLabel: 'ieri',
    entries: [{
      id: 'elena-18-pivot',
      type: 'cambio rotta',
      text: 'Ho smesso di inseguire cinque canzoni insieme. Per questa settimana ne tengo una sola: “Stand by Me”.',
      signals: { fire: 5, brick: 2, map: 6, zap: 2 },
    }],
  },
  {
    id: 'federico-day-30',
    person: 'Federico G.',
    initials: 'FG',
    color: '#fff0b8',
    day: 30,
    total: 30,
    dateLabel: '2 giorni fa',
    entries: [{
      id: 'federico-30-completion',
      type: 'completamento',
      text: 'Trenta giorni dopo, riesco a suonare il brano dall’inizio alla fine. Non perfetto: mio.',
      signals: { fire: 16, brick: 9, map: 7, zap: 5, vetta: 12 },
    }],
  },
]

export const questsCompleted = [
  {
    id: 1,
    category: 'Musica',
    title: 'I miei primi 4 accordi senza scorciatoie',
    author: 'Marta Rinaldi',
    authorVerifiedVia: 'quest',
    duration: '30 giorni',
    success: '84%',
    clones: 126,
    recencyDays: 12,
    color: '#cfe0ff',
    path: ['Postura', 'Dita', 'Cambi', 'Prima canzone'],
    listing: {
      type: 'corso',
      coach: 'Marta Rinaldi',
      rating: '4.8 · 42 recensioni',
      price: 39,
      premiumPrice: 69,
      hasPrivateRoom: true,
      hasLiveSessions: true,
      activationStatus: 'attiva',
      activationDetail: '18/24 posti',
      level: 'Principiante',
    },
  },
  {
    id: 2,
    category: 'Benessere',
    title: '21 mattine senza telefono',
    author: 'Giorgio Lodi',
    authorVerifiedVia: 'quest',
    duration: '21 giorni',
    success: '77%',
    clones: 94,
    recencyDays: 6,
    color: '#ffe0c5',
    path: ['Sveglia', 'Attrito', 'Routine', 'Autonomia'],
    listing: null,
  },
  {
    id: 3,
    category: 'Cucina',
    title: 'Otto piatti, una spesa intelligente',
    author: 'Nadia Pavesi',
    authorVerifiedVia: 'credentials',
    duration: '60 giorni',
    success: '71%',
    clones: 68,
    recencyDays: 24,
    color: '#d9ead7',
    path: ['Dispensa', 'Basi', 'Tempi', 'Menu'],
    listing: {
      type: 'consulenza',
      coach: 'Nadia Pavesi',
      rating: '4.7 · 19 recensioni',
      price: 45,
      premiumPrice: null,
      hasPrivateRoom: false,
      hasLiveSessions: true,
      activationStatus: null,
      activationDetail: 'Videochiamata individuale · 45 min',
      level: 'Intermedio',
    },
  },
  {
    id: 4,
    category: 'Lettura',
    title: 'Dieci pagine che restano',
    author: 'Anna Costa',
    authorVerifiedVia: 'quest',
    duration: '30 giorni',
    success: '89%',
    clones: 201,
    recencyDays: 18,
    color: '#e8ddff',
    path: ['Scelta', 'Ritmo', 'Appunti', 'Sintesi'],
    listing: {
      type: 'risorsa',
      coach: 'Anna Costa',
      rating: '4.9 · 18 recensioni',
      price: 18,
      premiumPrice: null,
      hasPrivateRoom: false,
      hasLiveSessions: false,
      activationStatus: null,
      activationDetail: 'PDF + checklist · disponibile subito',
      level: 'Principiante',
    },
  },
  {
    id: 5,
    category: 'Movimento',
    title: 'Correre i primi 5 km con costanza',
    author: 'Sara Neri',
    authorVerifiedVia: 'credentials',
    duration: '45 giorni',
    success: '81%',
    clones: 113,
    recencyDays: 3,
    color: '#d2ead8',
    path: ['Camminata', 'Fiato', 'Ritmo', 'Primi 5 km'],
    listing: {
      type: 'corso',
      coach: 'Sara Neri',
      rating: '4.7 · 31 recensioni',
      price: 29,
      premiumPrice: 54,
      hasPrivateRoom: true,
      hasLiveSessions: false,
      activationStatus: 'in_attesa',
      activationDetail: '7/10 iscritti, si attiva entro il 20 luglio',
      level: 'Principiante',
    },
  },
]
